[[main]]
name = "ホーム"
url = ""
weight = 1

[[main]]
name = "インフォメーション"
identifier = "post"
url = "post"
weight = 10

[[main]]
name = "ご挨拶"
identifier = "greeting"
url = "greeting"
weight = 20

[[main]]
name = "業務案内"
identifier = "business"
url = "business"
weight = 30

[[main]]
name = "弁護士紹介"
identifier = "introduce"
url = "introduce"
weight = 40

[[main]]
name = "アクセス"
identifier = "access"
url = "access"
weight = 50

[[main]]
name = "採用情報"
url = "recruit"
weight = 60
title = "recruit"
